name: cell-diffusion-env
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - ipykernel
  - pytorch
  - torchvision
  - torchaudio
  - diffusers
  - transformers
  - numpy
  - pandas
  - matplotlib
  - webdataset
  - scikit-learn
  - dgl
  - dgllife
  - wandb
  - pip:
      - quilt3
      - tifffile
      - einops
      - rdkit
      - black
      - ruff
      - accelerate
